# Generated by Django 2.2.15 on 2020-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_to_root', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
