# Generated by Django 2.2.15 on 2020-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_to_root', '0005_post_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
