# Generated by Django 2.2.20 on 2021-05-21 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_to_root', '0011_remove_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctf',
            old_name='img',
            new_name='file',
        ),
        migrations.AddField(
            model_name='ctf',
            name='cate',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
