# Generated by Django 2.2.20 on 2021-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_to_root', '0012_auto_20210521_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctf',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
